"""Add blog_post_id to BlogComment

Revision ID: 44316f8527df
Revises: d426640ccb33
Create Date: 2023-10-18 23:49:33.204087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44316f8527df'
down_revision = 'd426640ccb33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blog_post_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'blog_post', ['blog_post_id'], ['id'])
        batch_op.drop_column('course_mention')

    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('blog_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_mention', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('blog_post_id')

    # ### end Alembic commands ###
