"""Add category column to Course table

Revision ID: d426640ccb33
Revises: 7812f8c096c3
Create Date: 2023-10-17 13:10:48.914981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd426640ccb33'
down_revision = '7812f8c096c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))

    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
